[pinecone_credentials]
PINECONE_API_KEY = "87d21a17-cc6f-4e2d-a4fe-2e5a86ee6fa8"
PINECONE_ENVIRONMENT = "us-west4-gcp-free"
PINECONE_INDEX_NAME = "amazon-products"
HF_API_KEY = "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"

[delta_sharing_credentials]
shareCredentialsVersion=1
bearerToken="pyAbvJOzsqSe_LDz8fvrpi6fLU8XaOhPg1udcnVbBS_WOG6jk9W1SAPVy1amSQiN"
endpoint="https://nvirginia.cloud.databricks.com/api/2.0/delta-sharing/metastores/bea5b0c1-9f25-414a-aa42-ae76101d550d"
expirationTime="9999-12-31T23:59:59.999Z"